### ISSUE TITLE
⚒️ Fazer literal todo o trabalho, mano 🖥️ 

### ISSUE THREAD

**Issue by NattanSouza404** [fabin0casa/POO-Rest-API#1]
Acho bom fazer essa issue👍

**Comment by fabi0casa** [comment]
Mano, eu diria que o principal problema do nosso programa é que ele não existe ainda, acertaste na mosca

**Comment by NattanSouza404** [comment]
AGORA ELE EXISTE MANO

**Comment by fabi0casa** [comment]
ACABEI DE VER AQUI E ELE EXISTE MESMO MANO

**Comment by NattanSouza404** [comment]
@fabin0casa e eu fizemos o inexistente ser existente. A nossa ideia, o nosso programa, ele EXISTE DE VERDADE.
Foi uma honra combater ao seu lado, participando juntos dessa jornada Pokémon!
