### ISSUE TITLE
Decidir qual entidade usaremos

### ISSUE THREAD

**Issue by NattanSouza404** [fabin0casa/POO-Rest-API#16]
Auto-descritivo. Decidir a entidade que realizaremos o CRUD. Tinhamos Construção como ideia, mas pode mudar.

Mande ideias.

**Comment by NattanSouza404** [comment]
Algum produto? Pessoas? Serviços? Eventos?

Um site secreto da deep web ou FBI, planos secretos de construir a maior Fatec já vista. Detetive:
![image](https://github.com/user-attachments/assets/9745efcd-fb5f-4ddf-ad7d-28ffbab352c7)

Mano, missões secretas (objetivo: roubar a Lua, minion encarregado, data, descrição)
![image](https://github.com/user-attachments/assets/4bf013cf-17ed-45d7-8dbc-1f4c98f6d798)

Repositório de aliens do Ben 10, fundação SCP, catálogo de criaturas:
![image](https://github.com/user-attachments/assets/12cf02ea-e6b8-4831-954b-2f4727603251)

**Comment by fabi0casa** [comment]
Ólea mano, baseado no catologo do ben 10 e dos SCP, eu pensei em fazer de pokemon:
![image](https://github.com/user-attachments/assets/f286608a-fc9c-43d0-a446-e5d574dfb89c)
de repente se vc quiser da pra gente colocar imagem tbm, mas ai seria um tramite a mais pra tramitar
tava pensando na gente se basear nesse site: https://www.pokemon.com/br/pokedex/glimmora

**Comment by NattanSouza404** [comment]
Mano, acho que é só decidir outro monstrinho/criatura para catalogarmos.
Ter um frontend lindo pra mostrar o bicho seria legal.
Ser for usar imagem, é bom colocar um limite de tamanho, por que se não o site fica pesado.

**Comment by fabi0casa** [comment]
Olha, por mim seria o pokemon msm, não consigo pensar em algo melhor
E das imagens mano, gepetto falou que é bom (mais performático) salvar os arquivos numa pasta do projeto e salvar só o caminho delas como string no banco de dados, botar limite de tamanho de arquivo e dimensionamento, e não deixar o cara colocar um arquivo que não seja `.jpeg`, `.png` ou `.webp`

**Comment by NattanSouza404** [comment]
Foi decidido que usaremos o pokémon mesmo, eu sugeri usar a estética da 5ª geração, pixelada e tal:

Os atributos que pensei, junto com as ideias do @fabin0casa foram (com esses nomes):
- id
- nome
- numero_dex
- especie
- tipo_primario
- tipo_secundario
- descricao
- altura
- peso
- url_imagem

**Comment by fabi0casa** [comment]
por mim tá bom
