### ISSUE TITLE
Arrumar o índice do MongoDB

### ISSUE THREAD

**Issue by NattanSouza404** [fabin0casa/POO-Rest-API#18]
Deixar o Número Dex verdadeiramente único (fazer o Spring fazer o trabalho dele).

**Comment by fabi0casa** [comment]
agora ele tá criando o indice mano:
![image](https://github.com/user-attachments/assets/f171bd2c-e842-412e-8dc7-05b5c0c58c76)
MAS, provavelmente pra funcionar ai vc terá q dropar o seu banco e subir ele dnv

**Comment by NattanSouza404** [comment]
Realmente foe arrumado. Não precisei dropar não.
