### ISSUE TITLE
[Bônus 2] Tratamento de exceções

### ISSUE THREAD

**Issue by NattanSouza404** [fabin0casa/POO-Rest-API#3]
Seria tratar bem as exceções do programa, criar exceções customizadas e tal.

**Comment by NattanSouza404** [comment]
Ideias de exceção:
- Alguns campos não podem ser nulos;
     - Tipo primário;
     - Nome;
     - Numero Dex;
- Numero Dex não pode ser negativo;
- Peso e altura não pode ser negativo;
- Pokémon só não pode ser cadastrado com nenhum tipo existente (não existe o tipo "demônio", só fogo, água, grama etc);
- Tamanho dos valores não podem ser infinitos;

**Comment by NattanSouza404** [comment]
Pela minha parte, considero feito. É ver se tem algum erro ou outra coisa a adicionar, mas o bruto tá feito.

**Comment by fabi0casa** [comment]
![image](https://media.tenor.com/lztbLMEBDs4AAAAM/sonic-boom-knuckles.gif)
