### ISSUE TITLE
Criar estrutura inicial do projeto

### ISSUE THREAD

**Issue by NattanSouza404** [fabin0casa/POO-Rest-API#6]
Ir no site [Start Spring IO](https://start.spring.io/) e criar a estrutura inicial do projeto, usando Java 21 e Maven:
- Dependência do Banco (MongoDB)
- Lombok
- JPA
- Spring Boot DevTools
- Spring Web
 
![image](https://github.com/user-attachments/assets/d88f377d-588a-4d3b-b41a-8b9ff8577aa7)

**Comment by NattanSouza404** [comment]
Creio que a estrutura do projeto foi criada com sucesso. Fiz assim:

![image](https://github.com/user-attachments/assets/4fe33534-dac0-4cc7-9cb2-5652226cd28f)
![image](https://github.com/user-attachments/assets/d13ffae5-908a-496e-8605-7ce9f4d4946b)

Aproveitei e adicionei a estrutura do front, seguindo o padrão do professor.
Supostamente o site fica nessa pasta (do jeito que o Spring Boot quer). E aí quando a aplicação subir, conseguiríamos acessar o site pela mesma porta que o nosso servidor subiu.
Pelo database não estar configurado, teremos que testar isso depois.

![image](https://github.com/user-attachments/assets/92167a41-f837-4d45-bfcd-d0feac5f588c)

**Comment by fabi0casa** [comment]
boa

**Comment by NattanSouza404** [comment]
O
