### ISSUE TITLE
Criar o banco de dados onde a Entidade será persistida

### ISSUE THREAD

**Issue by NattanSouza404** [fabin0casa/POO-Rest-API#7]
Basicamente, disponibilizar um arquivo com os comandos necessários para criar o banco.
Aqui criaremos a estrutura onde persistiremos nossa entidade.

**Comment by fabi0casa** [comment]
criei um banco de dados com o nome de `banco_poo_prj2` e a coleção com o nome de `pokemon`:
![Captura de tela de 2024-11-18 18-36-17](https://github.com/user-attachments/assets/1f8bbc05-88af-4d42-888a-6d92d61bf185)

no mongo o bagulho é meio louco, não tem "tabelas", vc adiciona os dados de qualquer jeito lá e boa, se do nada o mano resolver colocar o dado numa coluna que não existe ele cria a nova coluna pra vc (sql gonna cry)
![image](https://github.com/user-attachments/assets/25d87347-2569-4c10-b43c-b4617d6591bc)

vou colocar o arquivo json q eu fiz na pasta do projeto

**Comment by NattanSouza404** [comment]
Boa @fabin0casa.
